:bookseries: cookbook

[[preface]]
== Preface

This is a collection of solutions to questions you might have while developing
web applications with the Lift Web Framework.((("Lift Web Framework", "prerequisites")))

The aim is to give a single, short answer to a specific question. When there's more than approach, or style, we'll give you one solution, but will point you at alternatives in the discussion.

<<InstallAndRunning>> will get you up and running with Lift, but in other respects this cookbook is aimed at practitioners and the questions they have asked. If this is the first time you've heard of Lift, you'll want to look at:

* http://simply.liftweb.net[_Simply Lift_]

* Torsten Uhlmann's _Instant Lift Web Applications How-to_ (PACKT Publishing)

* Timothy Perrett's _Lift in Action_ (Manning Publications)


[[Contributors]]
=== Contributors

I've mined the Lift mailing list for these recipes, but I'm not the only one.  Recipes have been contributed by((("Lift Cookbook", "contributers"))):


* Jono Ferguson, who's a Scala consultant based in Sydney, Australia. He can be found lurking on the Lift mailing list and occasionally helps out with Lift modules.((("Ferguson, Jono"))) Find him at https://twitter.com/jonoabroad and http://underscoreconsulting.com.

* Franz Bettag, who's been an enthusiastic Scala hacker for several years now. He joined the Lift team in January 2012 and actively tweets and blogs about his newest Scala adventures.((("Bettag, Franz"))) Find him at https://twitter.com/fbettag[https://twitter.com/fbettag].

* Marek Żebrowski.((("Żebrowski, Marek")))

* Peter Robinett, who's a web and mobile developer and a Lift committer. He can be found http://www.bubblefoundry.com[on the Web] and http://twitter.com/pr1001[on Twitter].((("Robinett, Peter")))

* Kevin Lau, who's a founder of few web apps with a focus in AWS cloud, iOS, and Lift.((("Lau, Kevin")))

* Tony Kay.((("Kay, Tony")))

[[jointhem]]
You should join them: <<AddRecipe>> tells you how.


=== Source

The text of this cookbook is at https://github.com/d6y/lift-cookbook[https://github.com/d6y/lift-cookbook].

You'll find projects for each chapter at https://github.com/LiftCookbook/[GitHub].


=== Updates

Follow https://twitter.com/liftcookbook[@LiftCookbook] on Twitter.

=== Software Versions

Except where otherwise indicated, the examples use Lift 2.5 with SBT
0.12 and Scala 2.9.

Lift 2.5 is also available for Scala 2.10.


=== Conventions Used in This Book

The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or by values determined by context.


[TIP]
====
This icon signifies a tip, suggestion, or general note.
====

[WARNING]
====
This icon indicates a warning or caution.
====

=== Using Code Examples

This book is here to help you get your job done. In general, if this book includes code examples, you may use the code in this book in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require pass:[<phrase role='keep-together'>permission.</phrase>]

We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “_Lift Cookbook_ by Richard Dallaway (O’Reilly). Copyright 2013 Richard Dallaway, 978-1-449-36268-3.”

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<email>permissions@oreilly.com</email>].

=== Safari® Books Online

[role = "safarienabled"]
[NOTE]
====
pass:[<ulink role="orm:hideurl:ital" url="http://my.safaribooksonline.com/?portal=oreilly">Safari Books Online</ulink>] is an on-demand digital library that delivers expert pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/content">content</ulink>] in both book and video form from the world&#8217;s leading authors in technology and business.
====

Technology professionals, software developers, web designers, and business and creative professionals use Safari Books Online as their primary resource for research, problem solving, learning, and certification training.

Safari Books Online offers a range of pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/subscriptions">product mixes</ulink>] and pricing programs for pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/organizations-teams">organizations</ulink>], pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/government">government agencies</ulink>], and pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/individuals">individuals</ulink>]. Subscribers have access to thousands of books, training videos, and prepublication manuscripts in one fully searchable database from publishers like O’Reilly Media, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, Course pass:[<phrase role='keep-together'>Technology,</phrase>] and dozens pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/publishers">more</ulink>]. For more information about Safari Books Online, please visit us pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/">online</ulink>].

=== How to Contact Us

Please address comments and questions concerning this book to the publisher:

++++
<simplelist>
<member>O’Reilly Media, Inc.</member>
<member>1005 Gravenstein Highway North</member>
<member>Sebastopol, CA 95472</member>
<member>800-998-9938 (in the United States or Canada)</member>
<member>707-829-0515 (international or local)</member>
<member>707-829-0104 (fax)</member>
</simplelist>
++++

We have a web page for this book, where we list errata, examples, and any additional information. You can access this page at link:$$http://oreil.ly/lift-cookbook$$[].

To comment or ask technical questions about this book, send email to pass:[<email>bookquestions@oreilly.com</email>].

For more information about our books, courses, conferences, and news, see our website at link:$$http://www.oreilly.com$$[].

Find us on Facebook: link:$$http://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$http://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

=== Acknowledgments

These recipes exist because of the many contributions on the Lift mailing list, where _Liftafarians_, as they are known, generously give their time to ask questions, put together example projects, give answers, share alternatives, and chip in with comments. Thank you.

I also want to thank those who have provided corrections to the recipes, on the mailing list, GitHub, and Twitter.  No matter what else it means, writing on the Web and publishing on the Web has meant I've received some prompt, high-quality feedback.

I am indebted to the contributors who have taken the trouble to write new recipes for this book.


