Contributing, bug reports & getting help
----------------------------------------

How to add a new recipe to this Cookbook
----------------------------------------

Problem
~~~~~~~

You'd like to add a new page to this cookbook.

Solution
~~~~~~~~

If you're comfortable using Git, you can fork the repository and send a
push request.

Alternatively, download the template file, write your recipe, and email
to the Lift mailing list.

The template is:
https://raw.github.com/d6y/lift-cookbook/master/template.md[https://raw.github.com/d6y/lift-cookbook/master/template.md]

Discussion
~~~~~~~~~~

The cookbook is structured using Markdown and Pamflet. Each recipe is a
file with the same structure as the template file, and gives one good
solution to a problem. Feel free to discuss alternatives or related
concepts in the discussion section.

If you've forked the project from Github, you'll find all the pages in
the `docs` folder, with sub-folders for each section. The filenames are
used for ordering the pages and sections. Feel free to send pull
requests.

See Also
~~~~~~~~

* https://github.com/d6y/lift-cookbook/[This project on Github]
* http://daringfireball.net/projects/markdown/syntax[Markdown syntax
guide]
* http://pamflet.databinder.net/Pamflet.html[Pamflet]
* http://pamflet.databinder.net/Filenames+and+Page+Names.html[Pamflet
filenames and titles]
* http://pamflet.databinder.net/Source+Code+Highlighting.html[Formatting
source code]

How to report bugs
------------------

Problem
~~~~~~~

You've found a bug and want to report it.

Solution
~~~~~~~~

Discuss your findings on the Lift mailing list, saying what you're
seeing, and what you'd expect to see.

By all means look at https://github.com/lift/modules/issues[existing
issues] to see if your issue is there or recently fixed, but do not
raise a ticket unless asked to do so by a Lift committer on the mailing
list.

Discussion
~~~~~~~~~~

*"If Lift is not behaving as you expect, please ask questions about what
you're seeing. The ideal form of these questions is 'When I do X, my
Lift app does Y, but I expect it to do Z, why?' This provides a set of
language to discuss your application and the way that Lift responds to
requests. Perhaps there's a way of improving Lift. Perhaps there's a
concept that's different in Lift than you might be used to. Perhaps
there's a documentation issue that can help bridge the gap between what
Lift is doing and what you expect it to do. Most importantly, just
because Lift is behaving differently than you expect it to, it's not
necessarily a bug in Lift."* (from
http://lift.la/expected-behavior-in-the-lift-community[Expected Behavior
in the Lift community])

See Also
~~~~~~~~

* http://www.assembla.com/wiki/show/liftweb/Posting_example_code[How to
post a code example]
* http://www.assembla.com/wiki/show/liftweb/Creating_tickets[Creating
tickets]

